#!/usr/bin/env python3
"""Generate a long SystemVerilog file with errors at known, spread-out lines.

    dev/gen-diagnostic-fixture.py OUT.sv [MODULES]

Why this exists rather than a file under `demo/`: `demo/rtl/` is deliberately
clean -- it passes verible's full default rule set with no waivers at all, and
that contrast is something CLAUDE.md says to preserve. Which makes it exactly
the wrong material for measuring a feature that draws diagnostics. This
generates a measuring instrument instead: a file long enough to need a
scrollbar, with errors at line numbers you know in advance, so a screenshot can
be checked against arithmetic rather than eyeballed.

Used for M115 (diagnostic marks on the scrollbar). With the default 12 modules
it produces 174 lines with errors at 16, 44, 72, 100, 128 and 156 -- evenly
spaced, which is the property that makes the check sharp: the marks' pixel
spacing must be constant, and it only is if placement divides by the whole
buffer rather than by the visible window. That was the likeliest way to get the
feature subtly wrong, and it would have looked plausible on any file short
enough to fit on screen.

Do not put the output in the repo. It is deliberately broken code; `demo/` is
showcase material and every item there has to have actually been run.
"""

import sys


def generate(modules):
    lines = [
        # Exactly five comment lines plus the blank. The absolute line numbers
        # quoted in PLAN.md's M115 record were measured against this output, so
        # adding or removing a line here shifts every error and makes that
        # evidence unreproducible. Put new prose in this file's docstring.
        "// Generated by dev/gen-diagnostic-fixture.py -- a measuring instrument,",
        "// not showcase material. Deliberately contains errors at known lines,",
        "// so a screenshot of the scrollbar's diagnostic marks can be checked",
        "// against arithmetic instead of eyeballed. See PLAN.md's M115 record",
        "// for the measurements this file was built to make.",
        "",
    ]
    bad = []
    for m in range(modules):
        lines += [
            f"module blk_{m} #(parameter int W = 8) (",
            "    input  logic         clk_i,",
            "    input  logic         rst_ni,",
            "    input  logic [W-1:0] a_i,",
            "    output logic [W-1:0] y_o",
            ");",
            "  logic [W-1:0] r_q;",
            "  always_ff @(posedge clk_i or negedge rst_ni) begin",
            "    if (!rst_ni) r_q <= '0;",
        ]
        if m % 2 == 0:
            # An undeclared identifier: a reliable, unambiguous error from any
            # SystemVerilog server, and it also leaves `a_i` unused, which adds
            # a warning a few lines above it -- two severities to tell apart.
            bad.append(len(lines) + 1)
            lines.append(f"    else         r_q <= undeclared_signal_{m};")
        else:
            lines.append("    else         r_q <= a_i;")
        lines += ["  end", "  assign y_o = r_q;", "endmodule", ""]
    return lines, bad


def main():
    if len(sys.argv) not in (2, 3):
        sys.stderr.write("usage: gen-diagnostic-fixture.py OUT.sv [MODULES]\n")
        return 2
    out = sys.argv[1]
    modules = int(sys.argv[2]) if len(sys.argv) == 3 else 12
    lines, bad = generate(modules)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s: %d lines, errors at %s" % (out, len(lines), bad))
    return 0


if __name__ == "__main__":
    sys.exit(main())
