(setq out-file (getenv "OUT"))
(defun out (s) (append-to-file s nil out-file))
(defun st (tag) (redisplay t) (out (format "%-30s ws=%3d pt=%3d wend=%3d h=%d\n" tag (line-number-at-pos (window-start)) (line-number-at-pos (point)) (line-number-at-pos (window-end nil t)) (window-text-height))))
(defun try (tag form) (condition-case e (progn (eval form) (st tag)) (error (out (format "%-30s SIGNAL: %S\n" tag e)))))
(defun cl (tag) (setq this-command 'recenter-top-bottom) (try tag '(recenter-top-bottom)) (setq last-command 'recenter-top-bottom))
(set-frame-size (selected-frame) 80 24)
(switch-to-buffer "*t*")
(dotimes (i 100) (insert (format "line %d\n" (1+ i))))
(goto-char (point-min))
(redisplay t)
(st "start")
(try "C-v #1" '(scroll-up-command))
(try "C-v #2" '(scroll-up-command))
(try "C-v arg 3" '(scroll-up-command 3))
(try "C-v arg -3" '(scroll-up-command -3))
(try "M-v #1" '(scroll-down-command))
(try "M-v arg 3" '(scroll-down-command 3))
(goto-char (point-min)) (set-window-start nil (point-min)) (st "reset top")
(try "M-v at top" '(scroll-down-command))
(goto-char (point-min)) (set-window-start nil (point-min)) (forward-line 5) (st "line 6 ws 1")
(try "M-v at top pt 6" '(scroll-down-command))
(goto-char (point-max)) (st "after M->")
(try "C-v last page" '(scroll-up-command))
(goto-char (point-min)) (set-window-start nil (point-min))
(dotimes (i 12) (condition-case e (progn (scroll-up-command) (st (format "C-v loop #%d" (1+ i)))) (error (out (format "C-v loop #%d SIGNAL: %S\n" (1+ i) e)))))
(try "M-v from last page" '(scroll-down-command))
;; recenter
(goto-char (point-min)) (forward-line 49) (set-window-start nil (point-min)) (st "line 50 ws 1")
(try "recenter nil" '(recenter))
(try "recenter 0" '(recenter 0))
(try "recenter -1" '(recenter -1))
(try "recenter 3" '(recenter 3))
(try "recenter -3" '(recenter -3))
(setq last-command nil)
(cl "C-l #1") (cl "C-l #2") (cl "C-l #3") (cl "C-l #4")
(setq last-command nil)
(try "C-l arg 2" '(recenter-top-bottom 2))
(goto-char (point-min)) (forward-line 2) (set-window-start nil (point-min)) (setq last-command nil) (st "line 3 ws 1")
(cl "C-l near top #1") (cl "C-l near top #2") (cl "C-l near top #3")
(goto-char (point-max)) (forward-line -2) (setq last-command nil) (st "line 99")
(cl "C-l near end #1") (cl "C-l near end #2") (cl "C-l near end #3")
;; point placement when scrolled off
(goto-char (point-min)) (set-window-start nil (point-min)) (forward-line 8) (st "line 9 ws 1")
(try "C-v from line 9" '(scroll-up-command))
(goto-char (point-min)) (set-window-start nil (point-min)) (forward-line 22) (st "line 23 ws 1 (last visible)")
(try "C-v from line 23" '(scroll-up-command))
(goto-char (point-min)) (set-window-start nil (point-min)) (scroll-up-command) (scroll-up-command) (st "two pages")
(goto-char (window-end nil t)) (forward-line -1) (st "pt last visible")
(try "M-v pt last visible" '(scroll-down-command))
(out (format "pos-visible: point=%S pmin=%S\n" (pos-visible-in-window-p (point)) (pos-visible-in-window-p (point-min))))
;; set-window-start then a command: does redisplay keep it?
(goto-char (point-min)) (forward-line 49) (set-window-start nil (point-min)) (st "pt 50 ws 1 (set-window-start, pt off)")
(kill-emacs 0)
