(setq out-file (getenv "OUT"))
(defun out (s) (append-to-file s nil out-file))
(defun st (tag) (redisplay t) (out (format "%-30s ws=%3d pt=%3d wend=%3d h=%d\n" tag (line-number-at-pos (window-start)) (line-number-at-pos (point)) (line-number-at-pos (window-end nil t)) (window-text-height))))
(defun try (tag form) (condition-case e (progn (eval form) (st tag)) (error (out (format "%-30s SIGNAL: %S\n" tag e)))))
(set-frame-size (selected-frame) 80 24)
(switch-to-buffer "*t*")
(dotimes (i 100) (insert (format "line %d\n" (1+ i))))
(goto-char (point-min)) (redisplay t)
(goto-char (point-min)) (forward-line 69) (set-window-start nil (point)) (goto-char (point-min)) (forward-line 70) (st "ws 70 pt 71")
(try "C-v arg 50 from ws70" '(scroll-up-command 50))
(goto-char (point-min)) (forward-line 29) (set-window-start nil (point)) (st "ws 30")
(try "M-v arg 50 from ws30" '(scroll-down-command 50))
(goto-char (point-min)) (forward-line 29) (set-window-start nil (point)) (st "ws 30 again")
(try "M-v arg 29 from ws30" '(scroll-down-command 29))
(goto-char (point-min)) (set-window-start nil (point-min)) (forward-line 40) (st "pt 41 ws 1 -> redisplay")
(goto-char (point-min)) (forward-line 49) (set-window-start nil (point)) (goto-char (point-min)) (st "ws 50 pt 1 -> redisplay")
(kill-emacs 0)
