(setq out-file (getenv "OUT"))
(defun out (s) (append-to-file s nil out-file))
(defun st (tag) (redisplay t) (out (format "%-30s ws=%3d pt=%3d wend=%3d h=%d\n" tag (line-number-at-pos (window-start)) (line-number-at-pos (point)) (line-number-at-pos (window-end nil t)) (window-text-height))))
(defun try (tag form) (condition-case e (progn (eval form) (st tag)) (error (out (format "%-30s SIGNAL: %S\n" tag e)))))
(defun setws (n) (goto-char (point-min)) (forward-line (1- n)) (set-window-start nil (point)) (redisplay t))
(set-frame-size (selected-frame) 80 24)
(switch-to-buffer "*t*")
(dotimes (i 100) (insert (format "line %d\n" (1+ i))))
(goto-char (point-min)) (redisplay t)
(setws 82) (st "ws 82") (try "C-v from 82 (->101?)" '(scroll-up-command))
(setws 81) (st "ws 81") (try "C-v from 81 (->100)" '(scroll-up-command))
(setws 83) (st "ws 83") (try "C-v from 83 (->102?)" '(scroll-up-command))
(setws 80) (st "ws 80") (try "C-v from 80 (->99)" '(scroll-up-command))
(setws 30) (try "M-v arg 30 from 30" '(scroll-down-command 30))
(setws 31) (try "M-v arg 30 from 31" '(scroll-down-command 30))
(setws 2) (try "M-v from 2" '(scroll-down-command))
(setws 20) (goto-char (point-min)) (forward-line 30) (st "ws 20 pt 31") (try "recenter nil pt31" '(recenter))
(setws 1) (goto-char (point-min)) (forward-line 49) (try "recenter 25 (>h)" '(recenter 25))
(setws 1) (goto-char (point-min)) (forward-line 49) (try "recenter -25 (<-h)" '(recenter -25))
(kill-emacs 0)
