(defun st (tag) (princ (format "%-28s ws-line=%3d pt-line=%3d win-h=%d text-lines=%d\n" tag (line-number-at-pos (window-start)) (line-number-at-pos (point)) (window-height) (window-text-height))))
(defun try (tag form) (condition-case e (progn (eval form) (st tag)) (error (princ (format "%-28s SIGNAL: %S\n" tag e)))))
(switch-to-buffer "*t*")
(dotimes (i 100) (insert (format "line %d\n" (1+ i))))
(goto-char (point-min))
(princ (format "vars: next-screen-context-lines=%S recenter-positions=%S scroll-error-top-bottom=%S scroll-preserve-screen-position=%S scroll-margin=%S\n" next-screen-context-lines recenter-positions scroll-error-top-bottom scroll-preserve-screen-position scroll-margin))
(st "start")
(try "C-v #1" '(scroll-up-command))
(try "C-v #2" '(scroll-up-command))
(try "C-v arg 3" '(scroll-up-command 3))
(try "M-v #1" '(scroll-down-command))
(try "M-v arg 3" '(scroll-down-command 3))
(goto-char (point-min)) (set-window-start nil (point-min))
(try "M-v at top" '(scroll-down-command))
(goto-char (point-max))
(st "after M-> (no redisplay)")
(try "C-v near end" '(scroll-up-command))
(try "C-v at end again" '(scroll-up-command))
;; recenter cycle
(goto-char (point-min)) (forward-line 49) (set-window-start nil (point-min))
(st "line 50, ws 1")
(try "recenter nil" '(recenter))
(try "recenter 0" '(recenter 0))
(try "recenter -1" '(recenter -1))
(try "recenter 3" '(recenter 3))
(setq last-command nil)
(try "C-l #1" '(recenter-top-bottom))
(setq last-command 'recenter-top-bottom)
(try "C-l #2" '(recenter-top-bottom))
(try "C-l #3" '(recenter-top-bottom))
(try "C-l #4" '(recenter-top-bottom))
(setq last-command nil)
(try "C-l arg 2" '(recenter-top-bottom 2))
;; point moves when it scrolls off
(goto-char (point-min)) (set-window-start nil (point-min))
(try "C-v from line 1" '(scroll-up-command))
(princ (format "pos-visible-p point=%S  point-min=%S\n" (pos-visible-in-window-p (point)) (pos-visible-in-window-p (point-min))))
(goto-char (point-min)) (set-window-start nil (point-min)) (forward-line 5)
(try "C-v from line 6" '(scroll-up-command))
(goto-char (point-min)) (set-window-start nil (point-min)) (forward-line 8)
(try "C-v from line 9" '(scroll-up-command))
;; scroll-down when point is beyond the window bottom after scrolling back
(goto-char (point-min)) (set-window-start nil (point-min)) (scroll-up-command) (scroll-up-command) (goto-char (window-end nil t)) (forward-line -1)
(st "point on last visible line")
(try "M-v then" '(scroll-down-command))
;; near end: last page
(goto-char (point-min)) (set-window-start nil (point-min))
(dotimes (i 20) (condition-case e (scroll-up-command) (error (princ (format "C-v loop #%d SIGNAL: %S\n" (1+ i) e)))))
(st "after C-v loop")
